#FROM ubuntu:latest
FROM node:alpine

WORKDIR /app/

COPY . ./

RUN npm install -g @angular/cli

RUN npm install --force

ENV NODE_ENV development
EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0"]
LABEL authors="rompasaurus"

